apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    name: frontend
    tag: ui
spec:
  containers:
    - name: frontend-container
      image: hamzausmani021/devopsproject-devopsui:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
