apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    name: frontend
  ports:
    - nodePort: 30001
      protocol: TCP
      port: 4200
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    name: backend-api
  ports:
    - port: 5001
      targetPort: 80
      nodePort: 30010
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    name: backend-auth
  ports:
    - port: 5178
      targetPort: 80
      nodePort: 30011
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    name: devops-db
  ports:
    - port: 1433
      targetPort: 1433
