apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    name: client
spec:
  containers:
    - name: mssqlclient
      image: mcr.microsoft.com/mssql-tools
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 82
      command: ["sleep", "3600"]

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    name: client
  ports:
    - port: 6000
      targetPort: 82
